### ISSUE TITLE
Hi we are looking for golang developer

### ISSUE THREAD

**Issue by sheenhx** [tyomhk2015/gocoin#16]
Hi Tyo,

We are looking for Golang developers focusing on crypto and AI , if you are interested write me hr@matchx.ai

**Comment by tyomhk2015** [comment]
@sheenhx 

Dear Sheen 👋

Thank you for taking the time letting me know about MatchX GmbH recruiting Golang developers. 💻

I am truly in curious and enthusiastic on crypto currencies and AI. 

Thanks to your LinkedIn, I was able to find the detail of your current recruitment. ([Link](https://www.linkedin.com/jobs/view/2800742990/)) 📝

However, after reading the job post, I found that I could not meet some of the 'Skills And Experience' requirements.

Once I make up my skills, I will contact the address you have shared. 💪

Again, I greatly appreciate for contacting me.

Best regards, 

Tyo
